### Test GET / endpoint
GET http://localhost:40000/ HTTP/1.1
Content-Type: application/json

### Test POST /calculadora endpoint
POST http://localhost:40000/calculadora HTTP/1.1
Content-Type: application/json

{
    "num1": 10,
    "num2": 20,
    "operacao": "/"
}
